GET http://localhost:3000/

### Check Elasticsearch connector

GET http://localhost:3000/api/elasticsearch

### Create document

POST http://localhost:3000/api/elasticsearch/blogs
Content-Type: application/json

{
   "name": "The second blog",
    "description": "Nothing",
    "author": "Quan Phat",
    "pages": 99
}

### Search
GET http://localhost:3000/api/elasticsearch/blogs?query=second